build karch:
    #!/usr/bin/env bash
    set -euxo pipefail
    RUST_TARGET={{ karch }}-unknown-none
    RUST_PROFILE=dev
    RUSTFLAGS="-C relocation-model=static" cargo build --target ${RUST_TARGET} --profile ${RUST_PROFILE}

clean:
    cargo clean
    rm -f kernel
